export { default as InputPassword } from './InputPassword'
export { default as InputFloating } from './InputFloating'
export { default as InputAboutSendMail } from './InputAboutSendMail'
export { default as InputCustom } from './InputCustom'
export { default as InputSelect } from './InputSelect'
export { default as InputFile } from './InputFile'
